name: Build Docker Image (Latest Only to Docker Hub)

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  packages: write # I když nepoužíváme GHCR, ponechávám pro jistotu
  actions: write

jobs:
  validate-tag-semver:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check_tag.outputs.valid }}
    steps:
      - name: Check if tag follows SemVer
        id: check_tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+|-beta\.[0-9]+|-rc\.[0-9]+)?$ ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: validate-tag-semver
    runs-on: ubuntu-latest
    if: needs.validate-tag-semver.outputs.valid == 'true'
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Run only once per release
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Checkout code
        uses: actions/checkout@v4.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Krok 'Login to GitHub Container Registry' byl odstraněn.

      - name: Generate Docker metadata (latest only)
        id: meta-latest
        uses: docker/metadata-action@v5.8.0
        with:
          # Pouze Docker Hub image
          images: |
            name=slabak007/romm
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.version=latest
            org.opencontainers.image.title="rommapp/romm"
            org.opencontainers.image.description="RomM (ROM Manager) allows youm to scan, enrich, and browse your game collection with a clean and responsive interface. With support for multiple platforms, various naming schemes and custom tags, RomM is a must-have for anyone who plays on emulators."
            org.opencontainers.image.licenses="AGPLv3"

      - name: Set version
        run: |
          sed -i 's/<version>/latest/' backend/__version__.py

      - name: Build and Push full image with 'latest' tag
        id: build-full-latest
        uses: docker/build-push-action@v6.18.0
        with:
          file: docker/Dockerfile
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta-latest.outputs.tags }}
          labels: ${{ steps.meta-latest.outputs.labels }}
          target: full-image
